# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 736)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #D1DBCB;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: white;\n"
"    background-color:rgb(45, 45, 45);\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #fdf6e3;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #fdf6e3*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"     #D1DBCB, stop: 1 #b2b6af);*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"\n"
" \n"
"    padding: 3px;\n"
"    border-style: solid;\n"
"    border: 1px solid rgb(131, 131, 131);\n"
"    border-radius:12;\n"
"}\n"
"QLabel{\n"
"    font-size:10pt; \n"
"       font-weight:600;\n"
"    color:white;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #fdf6e3;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"    #D1DBCB, stop: 1 #b2b6af);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #fdf6e3;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"     stop: 0 #D1DBCB, stop: 1 #b2b6af);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"#D1DBCB, stop: 1 #b2b6af);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"    #D1DBCB, stop: 1 #b2b6af);\n"
"}\n"
"\n"
"QScrollArea:focus {\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
"      #D1DBCB, stop: 0.5 #b2b6af, stop: 1 #D1DBCB);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
"      #D1DBCB, stop: 1 #b2b6af);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0\n"
"      #D1DBCB, stop: 1 #b2b6af);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"      #D1DBCB, stop: 0.5 #b2b6af, stop: 1 #D1DBCB);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0\n"
"      #D1DBCB, stop: 1 #b2b6af);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #b2b6af,\n"
"      stop: 1 #D1DBCB);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #b2b6af,\n"
"    stop:0.5 #b56c17 stop:1 #D1DBCB);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar {\n"
"    border: 1px transparent #323232;\n"
"    background: 1px solid #323232;\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #b2b6af;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #fdf6e3;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #fdf6e3);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #fdf6e3,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #fdf6e3;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:#403f3f;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 19))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setStyleSheet("background-color:#403f3f;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_4.setContentsMargins(9, 10, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.frame_16)
        self.label_20.setMinimumSize(QtCore.QSize(110, 0))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_16)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.github = QtWidgets.QPushButton(self.frame_4)
        self.github.setObjectName("github")
        self.verticalLayout_9.addWidget(self.github)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("background-color:#403f3f;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.window_title_frame = QtWidgets.QHBoxLayout(self.frame_8)
        self.window_title_frame.setContentsMargins(0, 0, 0, 0)
        self.window_title_frame.setObjectName("window_title_frame")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_button = QtWidgets.QPushButton(self.frame_9)
        self.menu_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/panel/assets/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon)
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_4.addWidget(self.menu_button)
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.window_title_frame.addWidget(self.frame_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.window_title_frame.addItem(spacerItem)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setStyleSheet("color:black;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Edo SZ")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.window_title_frame.addWidget(self.frame_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.window_title_frame.addItem(spacerItem1)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize_button = QtWidgets.QPushButton(self.frame_10)
        self.minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/panel/assets/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon1)
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout_3.addWidget(self.minimize_button)
        self.maxmize_button = QtWidgets.QPushButton(self.frame_10)
        self.maxmize_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/panel/assets/maxmize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxmize_button.setIcon(icon2)
        self.maxmize_button.setObjectName("maxmize_button")
        self.horizontalLayout_3.addWidget(self.maxmize_button)
        self.exit_button = QtWidgets.QPushButton(self.frame_10)
        self.exit_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/panel/assets/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon3)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_3.addWidget(self.exit_button)
        self.window_title_frame.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_6)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_14)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.tab)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.formLayout = QtWidgets.QFormLayout(self.frame_12)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.title_input = QtWidgets.QLineEdit(self.frame_12)
        self.title_input.setObjectName("title_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title_input)
        self.label_6 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.artist_input = QtWidgets.QLineEdit(self.frame_12)
        self.artist_input.setObjectName("artist_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.artist_input)
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.album_input = QtWidgets.QLineEdit(self.frame_12)
        self.album_input.setObjectName("album_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.album_input)
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.album_artist_input = QtWidgets.QLineEdit(self.frame_12)
        self.album_artist_input.setObjectName("album_artist_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.album_artist_input)
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.author_input = QtWidgets.QLineEdit(self.frame_12)
        self.author_input.setObjectName("author_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.author_input)
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.genre_input = QtWidgets.QLineEdit(self.frame_12)
        self.genre_input.setObjectName("genre_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.genre_input)
        self.label_15 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.track_input = QtWidgets.QLineEdit(self.frame_12)
        self.track_input.setObjectName("track_input")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.track_input)
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.year_input = QtWidgets.QLineEdit(self.frame_12)
        self.year_input.setObjectName("year_input")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.year_input)
        self.label_13 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.duration_input = QtWidgets.QLineEdit(self.frame_12)
        self.duration_input.setAutoFillBackground(False)
        self.duration_input.setReadOnly(True)
        self.duration_input.setObjectName("duration_input")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.duration_input)
        self.label_10 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bitrate_input = QtWidgets.QLineEdit(self.frame_12)
        self.bitrate_input.setReadOnly(True)
        self.bitrate_input.setObjectName("bitrate_input")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bitrate_input)
        self.label_14 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.access_date_input = QtWidgets.QLineEdit(self.frame_12)
        self.access_date_input.setAutoFillBackground(False)
        self.access_date_input.setReadOnly(True)
        self.access_date_input.setObjectName("access_date_input")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.access_date_input)
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Nyala")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.modified_date_input = QtWidgets.QLineEdit(self.frame_12)
        self.modified_date_input.setAutoFillBackground(False)
        self.modified_date_input.setReadOnly(True)
        self.modified_date_input.setObjectName("modified_date_input")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.modified_date_input)
        self.save_metadata = QtWidgets.QPushButton(self.frame_12)
        self.save_metadata.setMinimumSize(QtCore.QSize(0, 0))
        self.save_metadata.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save_metadata.setStyleSheet("")
        self.save_metadata.setObjectName("save_metadata")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.save_metadata)
        self.artist_input.raise_()
        self.label_3.raise_()
        self.title_input.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.album_input.raise_()
        self.label_8.raise_()
        self.author_input.raise_()
        self.label_9.raise_()
        self.genre_input.raise_()
        self.track_input.raise_()
        self.label_12.raise_()
        self.year_input.raise_()
        self.label_13.raise_()
        self.duration_input.raise_()
        self.label_10.raise_()
        self.bitrate_input.raise_()
        self.label_14.raise_()
        self.access_date_input.raise_()
        self.label_11.raise_()
        self.modified_date_input.raise_()
        self.save_metadata.raise_()
        self.album_artist_input.raise_()
        self.label_15.raise_()
        self.label_4.raise_()
        self.verticalLayout_6.addWidget(self.frame_12)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.lyrics_input = QtWidgets.QTextEdit(self.tab_2)
        self.lyrics_input.setObjectName("lyrics_input")
        self.verticalLayout_10.addWidget(self.lyrics_input)
        self.save_lyrics = QtWidgets.QPushButton(self.tab_2)
        self.save_lyrics.setObjectName("save_lyrics")
        self.verticalLayout_10.addWidget(self.save_lyrics)
        self.verticalLayout_7.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.audio_cover = QtWidgets.QLabel(self.frame_13)
        self.audio_cover.setMinimumSize(QtCore.QSize(250, 250))
        self.audio_cover.setMaximumSize(QtCore.QSize(250, 250))
        self.audio_cover.setBaseSize(QtCore.QSize(0, 0))
        self.audio_cover.setText("")
        self.audio_cover.setPixmap(QtGui.QPixmap(":/panel/assets/default.jpg"))
        self.audio_cover.setObjectName("audio_cover")
        self.verticalLayout_11.addWidget(self.audio_cover)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cover_change = QtWidgets.QPushButton(self.frame_13)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/panel/assets/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cover_change.setIcon(icon4)
        self.cover_change.setObjectName("cover_change")
        self.horizontalLayout_7.addWidget(self.cover_change)
        self.cover_remove = QtWidgets.QPushButton(self.frame_13)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/panel/assets/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cover_remove.setIcon(icon5)
        self.cover_remove.setObjectName("cover_remove")
        self.horizontalLayout_7.addWidget(self.cover_remove)
        self.cover_download = QtWidgets.QPushButton(self.frame_13)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/panel/assets/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cover_download.setIcon(icon6)
        self.cover_download.setObjectName("cover_download")
        self.horizontalLayout_7.addWidget(self.cover_download)
        self.cover_view = QtWidgets.QPushButton(self.frame_13)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/panel/assets/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cover_view.setIcon(icon7)
        self.cover_view.setObjectName("cover_view")
        self.horizontalLayout_7.addWidget(self.cover_view)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_15 = QtWidgets.QFrame(self.frame_7)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout.setObjectName("gridLayout")
        self.sort_ds = QtWidgets.QPushButton(self.frame_15)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/panel/assets/alpha-sort-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sort_ds.setIcon(icon8)
        self.sort_ds.setObjectName("sort_ds")
        self.gridLayout.addWidget(self.sort_ds, 0, 2, 1, 1)
        self.sort_as = QtWidgets.QPushButton(self.frame_15)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/panel/assets/alpha-sort-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sort_as.setIcon(icon9)
        self.sort_as.setObjectName("sort_as")
        self.gridLayout.addWidget(self.sort_as, 0, 1, 1, 1)
        self.open_new_file = QtWidgets.QPushButton(self.frame_15)
        self.open_new_file.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.open_new_file.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/panel/assets/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_new_file.setIcon(icon10)
        self.open_new_file.setObjectName("open_new_file")
        self.gridLayout.addWidget(self.open_new_file, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_15)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 5, 1, 1)
        self.remove = QtWidgets.QPushButton(self.frame_15)
        self.remove.setIcon(icon5)
        self.remove.setObjectName("remove")
        self.gridLayout.addWidget(self.remove, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_15)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_15)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 6, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_15)
        self.playlist_table = QtWidgets.QTableWidget(self.frame_7)
        self.playlist_table.setRowCount(0)
        self.playlist_table.setColumnCount(7)
        self.playlist_table.setObjectName("playlist_table")
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_5.addWidget(self.playlist_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ff7e00;\">Menu</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Not Implemented"))
        self.pushButton.setText(_translate("MainWindow", "Not Implemented"))
        self.pushButton_3.setText(_translate("MainWindow", "Not Implemented"))
        self.github.setText(_translate("MainWindow", "Github"))
        self.label_2.setText(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ff7e00;\">Tag</span><span style=\" font-size:20pt; font-weight:600;\"> Editor</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Title"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Artist: </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Album: </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Album artist: </span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Author</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Genre: </span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Track #: </span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Year: </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Duration</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Bit rate</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Last Access</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Last Modified</span></p></body></html>"))
        self.save_metadata.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Standard"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Lyrics</span></p></body></html>"))
        self.save_lyrics.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced"))
        self.cover_change.setText(_translate("MainWindow", "Change"))
        self.cover_remove.setText(_translate("MainWindow", "Remove"))
        self.cover_download.setText(_translate("MainWindow", "Download"))
        self.cover_view.setText(_translate("MainWindow", "View"))
        self.sort_ds.setText(_translate("MainWindow", "Sort Z-a"))
        self.sort_as.setText(_translate("MainWindow", "Sort A-z"))
        self.open_new_file.setText(_translate("MainWindow", "Open"))
        self.remove.setText(_translate("MainWindow", "remove"))
        item = self.playlist_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.playlist_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.playlist_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Artist"))
        item = self.playlist_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Album"))
        item = self.playlist_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Track"))
        item = self.playlist_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Year"))
        item = self.playlist_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Genre"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tag Editor INC</span></p></body></html>"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
